events {}
http {
  server {
    listen 80;
    server_name media-server;

    location /view/ {
      proxy_pass http://jellyfin:8096/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      rewrite ^/view/?(.*)$ /$1 break;
    }
    location /request/ {
      proxy_pass http://jellyseerr:5055/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      rewrite ^/request/?(.*)$ /$1 break;
    }
    location /sonarr/ {
      proxy_pass http://sonarr:8989/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      rewrite ^/sonarr/?(.*)$ /$1 break;
    }
    location /radarr/ {
      proxy_pass http://radarr:7878/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      rewrite ^/radarr/?(.*)$ /$1 break;
    }
    location /whisparr/ {
      proxy_pass http://whisparr:6969/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      rewrite ^/whisparr/?(.*)$ /$1 break;
    }
  }
}
